[package]
name = "chippy"
authors = ["Austin McBee"]
version = "0.1.0"
edition = "2021"


[dependencies]
rand = "0.8.5"
sdl2 = "0.35.2"
console = "0.15.0"
dialoguer = "0.10.1"
reqwest = { version = "0.11", features = ["blocking", "json"] }
